steps:
- name: 'gcr.io/cloud-builders/dotnet '
  args:
  - gcloud
  - functions
  - deploy
  - function-1
  - --region=us-central1
  - --source=.
  - --trigger-event google.storage.object.finalize
  - --runtime=dotnet3